study/bookshelf/urls.py
from django.urls import path, re_path
from rest_framework.routers import DefaultRouter
from . import views

app_name ='bookshelf'
router = DefaultRouter()
router.register(r'authors', views.AuthorViewSet)
router.register(r'books', views.BookViewSet)
router.register(r'publishers', views.PublisherViewSet)
router.register(r'bookshelves', views.BookshelfViewSet)
router.register(r'book-collections', views.BookCollectionViewSet)
router.register(r'book-serieses', views.BookSeriesViewSet)
router.register(r'reading-plans', views.ReadingPlanViewSet)
urlpatterns = [
    path('books/', views.BooksView.as_view(), name='bookshelf-books'),
    # path('books/', views.book_list, name='bookshelf-books'),
    path('books/<int:pk>/', views.BookView.as_view(), name='bookshelf-book'),
    path('books/pdf/<int:pk>/', views.BookPDFView.as_view()),
    # path('tag/<slug:tag_slug>/', views.book_list, name='book_list_by_tag'),
    path('tag/<str:tag_slug>/', views.BooksView.as_view(), name='book_list_by_tag'),
    path('authors/', views.AuthorsView.as_view(), name='bookshelf-authors'),
    path('authors/<int:pk>/', views.AuthorView.as_view(), name='bookshelf-author'),
    path('collections/', views.BookCollectionsView.as_view(), name='bookshelf-collections'),
    path('collections/<int:pk>/', views.BookCollectionView.as_view(), name='bookshelf-collection'),
    path('publishers/', views.PublishersView.as_view(), name='bookshelf-publishers'),
    path('publishers/<int:pk>/', views.PublisherView.as_view(), name='bookshelf-publisher'),
    path('brands/', views.BrandsView.as_view(), name='bookshelf-brands'),
    path('brands/<int:pk>/', views.BrandView.as_view(), name='bookshelf-brand'),
    path('serieses/', views.BookSeriesesView.as_view(), name='bookshelf-serieses'),
    path('serieses/<int:pk>/', views.BookSeriesView.as_view(), name='bookshelf-series'),
    path('books/urlsearch/<str:keywords>', views.SearchBooksView.as_view(), name='urlsearch'),
    path('books/booksearch/', views.BookSearch.as_view(), name='booksearch'),
    path('books/booksearchresult/', views.BookSearchResult.as_view(), name='booksearchresult'),
    path('plans/', views.ReadingPlansView.as_view(), name='bookshelf-plans'),
    path('plans/<int:pk>/', views.ReadingPlanView.as_view(), name='bookshelf-plan'),
    path('bookshelves/', views.BookshelvesView.as_view(), name='bookshelf-bookshelves'),
    path('bookshelves/<int:pk>', views.BookshelfView.as_view(), name='bookshelf-bookshelf'),
]

study/study/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from django.urls import path, include, re_path
from django.conf.urls import include as url_include
from django.views.generic import TemplateView
from rest_framework.authtoken.views import obtain_auth_token
# from . import settings
from .settings import pro as settings
from bookshelf.urls import router

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bookshelf/', include('bookshelf.urls')),
    # url(r'^api/token/', obtain_auth_token, name='api-token'),
    re_path(r'^api/', url_include(router.urls)),
    re_path(r'^$', TemplateView.as_view(template_name='bookshelf/index.html'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

study/bookshelf/models.py
from django.db import models
from taggit.managers import TaggableManager
from taggit.models import TagBase, GenericTaggedItemBase
from django.utils.text import slugify
from django.utils.translation import gettext, gettext_lazy as _


class MyTag(TagBase):
    slug = models.SlugField(verbose_name=_('slug'), unique=True, max_length=100, allow_unicode=True)

    def slugify(self, tag, i=None):
        slug = slugify(tag, allow_unicode=True)
        if i:
            slug += f'_{i}'
        return slug

    class Meta:
        verbose_name = _('tag')
        verbose_name_plural = _('tags')
        app_label = 'taggit'


class TaggedItem(GenericTaggedItemBase):
    id = models.BigAutoField(primary_key=True)
    tag = models.ForeignKey(MyTag, on_delete=models.CASCADE, related_name='%(app_label)s_%(class)s_items')


class Author(models.Model):
    DYNASTY = [
        ('上古', '上古'),
        ('夏', '夏'),
        ('商', '商'),
        ('西周', '西周'),
        ('东周', '东周'),
        ('春秋', '春秋'),
        ('战国', '战国'),
        ('秦', '秦'),
        ('西汉', '西汉'),
        ('东汉', '东汉'),
        ('魏', '魏'),
        ('蜀', '蜀'),
        ('吴', '吴'),
        ('西晋', '西晋'),
        ('东晋', '东晋'),
        ('南北朝', '南北朝'),
        ('隋', '隋'),
        ('唐', '唐'),
        ('五代', '五代'),
        ('北宋', '北宋'),
        ('南宋', '南宋'),
        ('元', '元'),
        ('明', '明'),
        ('清', '清'),
        ('民国', '民国'),
        ('现代', '现代'),
        ('当代', '当代'),
    ]

    NATION = [
        ('未知', '未知'),
        ('中国', '中国'),
        ('德国', '德国'),
        ('英国', '英国'),
        ('法国', '法国'),
        ('美国', '美国'),
        ('俄罗斯', '俄罗斯'),
        ('日本', '日本'),
        ('加拿大', '加拿大'),
        ('前苏联', '前苏联'),
        ('爱尔兰', '爱尔兰'),
        ('澳大利亚', '澳大利亚'),
        ('以色列', '以色列'),
        ('瑞士', '瑞士'),
        ('阿根廷', '阿根廷'),
        ('哥伦比亚', '哥伦比亚'),
        ('奥地利', '奥地利'),
        ('西班牙', '西班牙'),
        ('挪威', '挪威'),
        ('瑞典', '瑞典'),
        ('意大利', '意大利'),
        ('希腊', '希腊'),
        ('比利时', '比利时'),
        ('墨西哥', '墨西哥'),
        ('荷兰', '荷兰'),
        ('巴西', '巴西'),
        ('波兰', '波兰'),
        ('伊朗', '伊朗'),
        ('古巴', '古巴'),
        ('波斯', '波斯'),
        ('智利', '智利'),
        ('南非', '南非'),
        ('马来西亚', '马来西亚'),
        ('捷克', '捷克'),
        ('毛里求斯', '毛里求斯'),
        ('丹麦', '丹麦'),
    ]
    id = models.BigAutoField(primary_key=True)
    name = models.CharField(max_length=200, unique=True, verbose_name='姓名')
    chinese_name = models.CharField(max_length=200, blank=True, unique=True, verbose_name='中文名')
    nation = models.CharField(max_length=100, choices=NATION, verbose_name='国籍')
    dynasty = models.CharField(max_length=100, blank=True, choices=DYNASTY, verbose_name='朝代')
    intro = models.TextField(max_length=1500, blank=True, verbose_name='简介')
    photo = models.ImageField(upload_to='image/authors/', verbose_name='相片', null=True, blank=True)

    class Meta:
        ordering = ['nation', 'dynasty', 'chinese_name', ]

    def __str__(self):
        author_name = self.name
        if self.chinese_name:
            author_name = self.chinese_name
        if self.dynasty:
            return "[{0}] {1}".format(self.dynasty, author_name)
        else:
            return "[{0}] {1}".format(self.nation, author_name)

    @property
    def full_name(self):
        author_name = self.name
        if self.chinese_name:
            author_name = self.chinese_name
        if self.dynasty:
            return "[{0}] {1}".format(self.dynasty, author_name)
        else:
            return "[{0}] {1}".format(self.nation, author_name)

    @property
    def books(self):
        return self.book_set.all()


class Bookshelf(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100, null=True)
    description = models.CharField(max_length=200, null=True, blank=True, default=None)
    total_book_count = models.IntegerField()
    total_set_count = models.IntegerField()

    @property
    def books(self):
        return self.book_set.all()

    @property
    def total_book_count(self):
        return sum([book.book_count for book in self.books])

    @property
    def total_set_count(self):
        return len(self.books)

    def __str__(self):
        return self.name


class Publisher(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100, null=True, unique=True, verbose_name='名称')
    introduction = models.TextField(max_length=1500, blank=True, default=None, null=True, verbose_name='简介')

    def __str__(self):
        return self.name


class Brand(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100, null=True, unique=True, verbose_name='名称')
    introduction = models.TextField(max_length=1500, blank=True, default=None, null=True, verbose_name='简介')

    def __str__(self):
        return self.name


class BookSeries(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100, null=True, unique=True, verbose_name='名称')
    # books = models.ManyToManyField(Book)
    introduction = models.TextField(max_length=1500, blank=True, default=None, null=True, verbose_name='简介')

    def __str__(self):
        return self.name


class Book(models.Model):
    HARD_COVER = '精装'
    PAPER_COVER = '平装'
    BOX_SET = '盒装'
    WIRE_BOUND = '线装'
    BINDING_TYPE = [
        (HARD_COVER, HARD_COVER),
        (PAPER_COVER, PAPER_COVER),
        (BOX_SET, BOX_SET),
        (WIRE_BOUND, WIRE_BOUND),
    ]

    COATED_PAPER = '铜版纸'
    OFFSET_PAPER = '胶版纸'
    CHINA_PAPER = '宣纸'
    MUNKEN_PAPER = '轻型纸'
    PURE_QUALITY_PAPER = '纯质纸'
    WRITING_PAPER = '书写纸'
    ELEGANT_PAPER = '雅致纸'
    SPECIAL_PAPER = '特种纸'
    PAPER_TYPE = [
        (COATED_PAPER, COATED_PAPER),
        (OFFSET_PAPER, OFFSET_PAPER),
        (CHINA_PAPER, CHINA_PAPER),
        (MUNKEN_PAPER, MUNKEN_PAPER),
        (PURE_QUALITY_PAPER, PURE_QUALITY_PAPER),
        (WRITING_PAPER, WRITING_PAPER),
        (ELEGANT_PAPER, ELEGANT_PAPER),
        (SPECIAL_PAPER, SPECIAL_PAPER),
    ]

    CHINESE = '中文'
    TRADITIONAL_CHINESE = '繁体中文'
    ENGLISH = '英文'
    CHINESE_ENGLISH = '中文/英文'
    JANPANESE = '日文'
    LANGUAGES = [
        (CHINESE, CHINESE),
        (TRADITIONAL_CHINESE, TRADITIONAL_CHINESE),
        (ENGLISH, ENGLISH),
        (CHINESE_ENGLISH, CHINESE_ENGLISH),
        (JANPANESE, JANPANESE),
    ]

    HORIZONTAL = '横排'
    VERTICAL = '竖排'
    COMPOSE_TYPES = [
        (HORIZONTAL, HORIZONTAL),
        (VERTICAL, VERTICAL)
    ]

    NOT_READ = '未读'
    READING = '在读'
    FINISHED = '已读'
    READ_STATE = [
        (NOT_READ, NOT_READ),
        (READING, READING),
        (FINISHED, FINISHED)
    ]

    SCORES = [(i, i) for i in range(11)]

    id = models.AutoField(primary_key=True)
    isbn = models.CharField(max_length=30, unique=False)
    chinese_name = models.CharField(max_length=200, blank=True, default=None, verbose_name='中文译名', null=True)
    original_name = models.CharField(max_length=200, verbose_name='名称')
    authors = models.ManyToManyField(Author, blank=True)
    translator = models.CharField(max_length=100, blank=True, default=None, null=True, verbose_name='翻译/编纂/整理')
    publisher = models.ForeignKey(Publisher, on_delete=models.CASCADE, verbose_name='出版社', default=None,
                                  related_name='books', blank=True, null=True)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE, verbose_name='品牌', default=None, related_name='books',
                              blank=True, null=True)
    publish_date = models.DateField(verbose_name='出版日期', blank=True)
    book_series = models.ForeignKey(BookSeries, on_delete=models.CASCADE, verbose_name='丛书', default=None,
                                    related_name='books', blank=True, null=True)
    binding_type = models.CharField(max_length=20, choices=BINDING_TYPE, verbose_name='装帧', default=HARD_COVER)
    paper_type = models.CharField(max_length=20, blank=True, default=OFFSET_PAPER, choices=PAPER_TYPE,
                                  verbose_name='用纸')
    pages = models.IntegerField(verbose_name='页数', default=1)
    book_count = models.IntegerField(verbose_name='套装数量', default=1)
    language = models.CharField(max_length=30, choices=LANGUAGES, verbose_name='正文语种', default=CHINESE)
    compose_type = models.CharField(max_length=10, choices=COMPOSE_TYPES, verbose_name='排版', default=HORIZONTAL)
    price = models.FloatField(verbose_name='定价', blank=True)
    purchase_price = models.FloatField(verbose_name='购入价格', blank=True)
    purchase_date = models.DateField(verbose_name='购入日期', blank=True)
    thumb_image = models.ImageField(upload_to='image/books/', verbose_name='缩略图', blank=True, default=None)
    link = models.CharField(max_length=200, blank=True, default=None, verbose_name='商品链接', null=True)
    category = models.CharField(max_length=100, verbose_name='分类', blank=True)
    bookshelf = models.ForeignKey(Bookshelf, on_delete=models.CASCADE, default=1, verbose_name='所在书架')
    read_state = models.CharField(max_length=20, choices=READ_STATE, verbose_name='阅读状态', default=NOT_READ)
    introduction = models.TextField(max_length=5000, blank=True, default=None, null=True, verbose_name='简介')
    registered = models.CharField(max_length=20, choices=[('Yes', 'Yes'), ('No', 'No')], verbose_name="登记状态",
                                  default='No')
    edition = models.CharField(max_length=50, verbose_name='版次', default=None, blank=True, null=True)
    print = models.CharField(max_length=30, verbose_name='印次', default=None, blank=True, null=True)
    printed_number = models.CharField(max_length=30, verbose_name='印数', default=None, blank=True, null=True)
    my_score = models.IntegerField(choices=SCORES, verbose_name='我的评分', default=None, null=True, blank=True)
    douban_score = models.IntegerField(verbose_name='豆瓣评分', default=0, null=True, blank=True)

study/bookshelf/forms.py
from django import forms
from .models import Comment, Book, BookImage


class BookForm(forms.Form):
    registered = forms.Select()

    def update_registered_status(self):
        pass


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'body')


class BaseMultiImageFormSet(forms.BaseModelFormSet):
    def __init__(self, *args, **kwargs):
        super().__init__(self, *args, **kwargs)
        self.queryset = BookImage.objects.none()

MultiImageForm = forms.modelformset_factory(BookImage, fields=('image', ), formset=BaseMultiImageFormSet)

study/bookshelf/templates/bookshelf/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-theme.css' %}">
    <link rel="stylesheet" href="{% static 'css/hover.css' %}">
    {% block head %}{% endblock %}
</head>
<body>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <div id="content" class="main">
        {% block content%}
        {% endblock %}
    </div>
</body>
</html>

study/bookshelf/templates/bookshelf/book.html
{% extends "bookshelf/base.html" %}
{% load static %}

{% block title %}Book Details{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/book.css' %}">
{% endblock %}

{% block content%}
    <div id="bookname" class="top-head">
        <h1>{{ book.original_name }}</h1>
    </div>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% if book %}
        <div id="bookinfo">
            <div class="thumb">
                <img src="{{ book.thumb_image.url }}"/>
            </div>
            <div class="baseinfo">
                <table border="0">
                    <tr>
                        <td width="100px"><strong>ISBN：</strong></td>
                        <td>{{ book.isbn }}</td>
                    </tr>
                    <tr>
                        <td><strong>名称：</strong></td>
                        <td>{{ book.original_name }}</td>
                    </tr>
                    <tr>
                        <td><strong>中文名：</strong></td>
                        <td>{{ book.chinese_name }}</td>
                    </tr>
                    <tr>
                        <td><strong>作者：</strong></td>
                        <td>
                            {% for author in book.authors.all %}
                                <a href="{% url 'bookshelf:bookshelf-author' author.id %}">{{ author }}</a>
                            {% endfor %}
                        </td>
                    </tr>
                    {% if book.translator %}
                        <tr>
                            <td><strong>翻译/编纂/整理：</strong></td>
                            <td>{{ book.translator}}</td>
                        </tr>
                    {% endif %}
                    <tr>
                        <td><strong>定价：</strong></td>
                        <td>{{ book.price }}</td>
                    </tr>
                    <tr>
                        <td><strong>出版社：</strong></td>
                        <td>
                            <a href="{% url 'bookshelf:bookshelf-publisher' book.publisher.id %}">{{ book.publisher }}</a>
                        </td>
                    </tr>
                    {% if book.brand %}
                    <tr>
                        <td><strong>品牌：</strong></td>
                        <td>
                            <a href="{% url 'bookshelf:bookshelf-brand' book.brand.id %}">{{ book.brand }}</a>
                        </td>
                    </tr>
                    {% endif %}
                    <tr>
                        <td><strong>出版日期：</strong></td>
                        <td>{{ book.publish_date }}</td>
                    </tr>
                    {% if book.edition %}
                    <tr>
                        <td><strong>版次：</strong></td>
                        <td>{{ book.edition }}</td>
                    </tr>
                    {% endif %}
                    {% if book.edition %}
                    <tr>
                        <td><strong>印次：</strong></td>
                        <td>{{ book.print }}</td>
                    </tr>
                    {% endif %}
                    {% if book.edition %}
                    <tr>
                        <td><strong>印数：</strong></td>
                        <td>{{ book.printed_number }}</td>
                    </tr>
                    {% endif %}
                    {% if book.book_series %}
                    <tr>
                        <td><strong>丛书：</strong></td>
                        <td>
                            <a href="{% url 'bookshelf:bookshelf-series' book.book_series.id %}">{{ book.book_series }}</a>
                        </td>
                    </tr>
                    {% endif %}
                    <tr>
                        <td><strong>分类：</strong></td>
                        <td>{{ book.category }}</td>
                    </tr>
                    <tr>
                        <td><strong>装帧：</strong></td>
                        <td>{{ book.binding_type }}</td>
                    </tr>
                    <tr>
                        <td><strong>纸张：</strong></td>
                        <td>{{ book.paper_type }}</td>
                    </tr>
                    <tr>
                        <td><strong>语言：</strong></td>
                        <td>{{ book.language }}</td>
                    </tr>
                    <tr>
                        <td><strong>排版：</strong></td>
                        <td>{{ book.compose_type }}</td>
                    </tr>
                    <tr>
                        <td width="100px"><strong>页数：</strong></td>
                        <td>{{ book.pages }}</td>
                    </tr>
                    <tr>
                        <td><strong>册数：</strong></td>
                        <td>{{ book.book_count }}</td>
                    </tr>
                </table>
            </div>
            <div class="otherinfo">
                <table border="0">
                    <tr>
                        <td width="100px"><strong>商品链接：</strong></td>
                        <td><a href="{{ book.link }}">{{ book.link }}</a></td>
                    </tr>
                    <tr>
                        <td><strong>购入价格：</strong></td>
                        <td>{{ book.purchase_price }}</td>
                    </tr>
                    <tr>
                        <td><strong>购入日期：</strong></td>
                        <td>{{ book.purchase_date }}</td>
                    </tr>
                    <tr>
                        <td><strong>书架：</strong></td>
                        <td>{{ book.bookshelf }}</td>
                    </tr>
                    <tr>
                        <td><strong>阅读状态：</strong></td>
                        <td>{{ book.read_state }}</td>
                    </tr>
                    <tr>
                        <td><strong>登记状态：</strong></td>
                        <td>{{ book.registered }}</td>
                    </tr>
                    <tr>
                        <td><strong>简介：</strong></td>
                        {% if book.introduction %}
                            <td id="bookintro">{{ book.introduction }}</td>
                        {% else %}
                            <td>无</td>
                        {% endif %}
                    </tr>
                    <tr>
                        <td><strong>豆瓣评分：</strong></td>
                        <td>{{ book.douban_score }}</td>
                    </tr>
                    {% if book.my_comments %}
                    <tr>
                        <td><strong>我的点评：</strong></td>
                        <td>{{ book.my_comments }}</td>
                    </tr>
                    {% endif %}
                    {% if book.tags.all %}
                    <tr>
                        <td><strong>标签：</strong></td>
                        <td>
                            {% for tag in book.tags.all %}
                                <a href="{% url 'bookshelf:book_list_by_tag' tag.slug %}">
                                    {{ tag.name }}
                                </a>
                                {% if not forloop.last %}, {% endif %}
                            {% endfor %}
                        </td>
                    </tr>
                    {% endif %}
                </table>
            </div>
            {% if book.similar_books.all %}
            <div class="similarbooks">
                <label>您可能对这些书也感兴趣：</label>
                <ul>
                    {% for similar_book in book.similar_books.all %}
                        <li>
                            <a href="{% url 'bookshelf:bookshelf-book' similar_book.id %}">
                                <div class="similarbookthumb" title="{{ similar_book.original_name }}">
                                    <img src="{{ similar_book.thumb_image.url }}" height="80px" />
                                </div>
                            </a>
                        </li>
                    {% empty %}
                        未找到同类型的书.
                    {% endfor %}
                </ul>
            </div>
            {% endif %}
        </div>

        <br>

        <!-- <div id="comment_container">
            <h5>添加评论</h5>
            <div id="comment_section">
                <form method="POST">
                    {{ comment_form }}
                    {% csrf_token %}
                    <button class="btn btn-info" type="submit">评论 <i class="fas fa-comments"></i></button>
                </form>
                {% if comments %}
                    {% with book.num_of_comments as num_of_comments %}
                    <strong class="text-secondary">{{ num_of_comments }} Comment{{ num_of_comments|pluralize }}</strong>
                    {% endwith %}
                    <hr>
                    <ul>
                        {% for comment in comments %}
                            <li>
                                <div>
                                    <span>
                                        <strong class="text-info">{{ comment.name }} </strong>
                                        <small class="text-muted">{{ comment.created }}</small>
                                    </span>
                                    <p>
                                        {{ comment.body|safe }}
                                    </p>
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <strong class="text-secondary">No comments yet...</strong>
                {% endif %}
            </div>
        </div> -->
    {% endif %}
{% endblock %}

study/bookshelf/templates/bookshelf/bookpdf.html
{% extends "bookshelf/base.html" %}
{% load static %}

{% block title %}Book Details{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/bookpdf.css' %}">
{% endblock %}

{% block content%}
    <div id="bookname" class="top-head">
        <h1>{{ book.original_name }}</h1>
    </div>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% if book %}
        <div id="bookinfo">
            <div class="thumb">
                <img src="{{ book.thumb_image.path }}"/>
            </div>
            <div class="baseinfo">
                <table border="0">
                    <tr>
                        <td width="100px"><strong>ISBN：</strong></td>
                        <td>{{ book.isbn }}</td>
                    </tr>
                    <tr>
                        <td><strong>名称：</strong></td>
                        <td>{{ book.original_name }}</td>
                    </tr>
                    <tr>
                        <td><strong>中文名：</strong></td>
                        <td>{{ book.chinese_name }}</td>
                    </tr>
                    <tr>
                        <td><strong>作者：</strong></td>
                        <td>
                            {% for author in book.authors.all %}
                                <a href="{% url 'bookshelf:bookshelf-author' author.id %}">{{ author }}</a>
                            {% endfor %}
                        </td>
                    </tr>
                    {% if book.translator %}
                        <tr>
                            <td><strong>翻译/编纂/整理：</strong></td>
                            <td>{{ book.translator}}</td>
                        </tr>
                    {% endif %}
                    <tr>
                        <td><strong>定价：</strong></td>
                        <td>{{ book.price }}</td>
                    </tr>
                    <tr>
                        <td><strong>出版社：</strong></td>
                        <td>
                            <a href="{% url 'bookshelf:bookshelf-publisher' book.publisher.id %}">{{ book.publisher }}</a>
                        </td>
                    </tr>
                    <tr>
                        <td><strong>出版日期：</strong></td>
                        <td>{{ book.publish_date }}</td>
                    </tr>
                    {% if book.edition %}
                    <tr>
                        <td><strong>版次：</strong></td>
                        <td>{{ book.edition }}</td>
                    </tr>
                    {% endif %}
                    {% if book.edition %}
                    <tr>
                        <td><strong>印次：</strong></td>
                        <td>{{ book.print }}</td>
                    </tr>
                    {% endif %}
                    {% if book.edition %}
                    <tr>
                        <td><strong>印数：</strong></td>
                        <td>{{ book.printed_number }}</td>
                    </tr>
                    {% endif %}
                    {% if book.book_series %}
                    <tr>
                        <td><strong>丛书：</strong></td>
                        <td>
                            <a href="{% url 'bookshelf:bookshelf-series' book.book_series.id %}">{{ book.book_series }}</a>
                        </td>
                    </tr>
                    {% endif %}
                    <tr>
                        <td><strong>分类：</strong></td>
                        <td>{{ book.category }}</td>
                    </tr>
                    <tr>
                        <td><strong>装帧：</strong></td>
                        <td>{{ book.binding_type }}</td>
                    </tr>
                    <tr>
                        <td><strong>纸张：</strong></td>
                        <td>{{ book.paper_type }}</td>
                    </tr>
                    <tr>
                        <td><strong>语言：</strong></td>
                        <td>{{ book.language }}</td>
                    </tr>
                    <tr>
                        <td><strong>排版：</strong></td>
                        <td>{{ book.compose_type }}</td>
                    </tr>
                    <tr>
                        <td width="100px"><strong>页数：</strong></td>
                        <td>{{ book.pages }}</td>
                    </tr>
                    <tr>
                        <td><strong>册数：</strong></td>
                        <td>{{ book.book_count }}</td>
                    </tr>
                </table>
            </div>
            <div class="otherinfo">
                <table border="0">
                    <tr>
                        <td><strong>简介：</strong></td>
                        {% if book.introduction %}
                            <td id="bookintro">{{ book.introduction }}</td>
                        {% else %}
                            <td>无</td>
                        {% endif %}
                    </tr>
                    <tr>
                        <td><strong>豆瓣评分：</strong></td>
                        <td>{{ book.douban_score }}</td>
                    </tr>
                    {% if book.tags.all %}
                    <tr>
                        <td><strong>标签：</strong></td>
                        <td>
                            {% for tag in book.tags.all %}
                                <a href="{% url 'bookshelf:book_list_by_tag' tag.slug %}">
                                    {{ tag.name }}
                                </a>
                                {% if not forloop.last %}, {% endif %}
                            {% endfor %}
                        </td>
                    </tr>
                    {% endif %}
                </table>
            </div>
        </div>

        <br>
    {% endif %}
{% endblock %}